server:
  error:
    include-message: always

spring:
      data source:
        driver-class-name: org.h2.Driver
        password: "
        url: jdbc:h2:mem:testdb
        username: sa
      h2:
            console:
              enabled: true
              path: /h2-console
      jpa:
        database-plataform: org.hibernate.dialect.H2Dialect
        properties:
         hibernate:
            format_sql: true
            show_sql: true
        hibernate:
            ddl-auto: update


